spring.application.name=LibraryManager

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://100.111.94.63:5332/virtuallibrary
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.thymeleaf.cache=false

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.scope=email,profile

spring.jpa.show-sql=true

spring.jackson.deserialization.fail-on-unknown-properties=false
server.error.include-message=always
server.forward-headers-strategy=native

